controller_list:
  - name: fake_hg_arm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger1
      - finger2
initial:  # Define initial robot poses.
  - group: hg_arm
    pose: home